### 1. Önce Test Kullanıcısı Oluştur  (Eşleşen JSON Şablonu)
POST http://localhost:5118/api/auth/register
Content-Type: application/json

{
  "firstName": "Yahya Arda",
  "lastName": "Sandıkçı",
  "email": "arda@erms.com",
  "password": "123456",
  "role": 1,
  "departmentId": 1
}
###
### 2. Sonra O Kullanıcı İçin Test Talebi Oluştur 
POST http://localhost:5118/api/request
Content-Type: application/json

{
  "title": "Yeni Ekran Kartı Talebi",
  "description": "Yazılım geliştirme için ekran kartı gerekiyor bra.",
  "requesterId": 4,
  "priority": "High"
}

### 4. Yönetici Karar Veriyor 
PUT http://localhost:5118/api/approval/5/decision
Content-Type: application/json

{
  "decision": "Approved",
  "comment": "Tebrikler bra, bütçe ve departman onay verdi."
}

### 5. Talebe Ait Onay Geçmişini Listele 
GET http://localhost:5118/api/approval/request/3